pina/chebyshev.py, setup.py
An implementation which uses `np.polynomial.chebyshev.chebroots` looks more performant by 1 or 2 orders of magnitude:
However I do not know if the order of the roots is important, because it's **not** always the same. There are also some `1.e-16/17` instead of zeros.
Example:
```python
np.polynomial.chebyshev.chebroots() -> [ 9.51056516e-01  5.87785252e-01  7.37692017e-17 
-5.87785252e-01 -9.51056516e-01] 
np.roots() -> [-0.95105652 -0.58778525  0.95105652  0.58778525  0. ]
```
=> Use `np.polynomial.chebyshev.chebroots` instead of `np.roots`

pina/pinn.py
Small update in _compute_error(). Consider using `torch.linalg.vector_norm()` instead of manually compute it for efficiency reasons. Also using built in `pow` methods gives a small advantage in performance.
=> Small update in _compute_error() in pinn.py

pina/label_tensor.py, tests/test_label_tensor.py
Please consider this pull request for bug fixing. 
Consider the following example:
```
x = torch.rand((10, 2))    # create a tensor with two columns
variables  = ['u']              # create one variable
output = x.as_subclass(LabelTensor)   # x tensor points at LabelTensor class, and it is assigned to ouput
output.labels = variables                        # output labels are assigned
```
Notice that output is now an incorrect label tensor (two columns but only one is labelled). This can be avoided by adding a setter decorator on labels. This first checks the existence of a label in a label tensor, and if the tensor does not have a label we assign a new label (after testing compatibility of columns number and labels number).
=> Adding features to label tensor class

pina/model/__init__.py, pina/model/network.py, tests/test_network.py
Consider this pull request for feature enhancement. 
Currently PINA has implemented three main neural networks (FeedForward, DeepOnet, MultiFeedForward). It would be great if any user could pass an arbitrary model and this would be transformed to be compatible with PINA and label tensors. In this pull request I have created a custom class called `Network`  which converts a PINA model from a `torch.nn.Module` model. The constructor is called by passing a `torch.nn.Module` model, `input_variables` (list of input variables) and `output_variables` (list of output variables). Exception is raise if the model is not compatible with input/output variable shapes. Few simple test, testing the constructor and forward pass are added.
=> network added

pina/label_tensor.py, pina/pinn.py, pina/utils.py, tests/test_pinn.py
=> batch_enhancement

pina/pinn.py, tests/test_pinn.py
In this PR I'm adding support for Learning Rate schedulers in PINA with the addition of two parameters:
- `lr_scheduler_type `: Scheduler class to be used to allocate the object
- `lr_scheduler_kwargs`: Keyword arguments to be passed to the scheduler constructor.
I'm also adding `optimizer_kwargs ` to enable passing keyword arguments to the optimizer constructor.
=> Enable usage of Learning Rate schedulers

pina/pinn.py
Add the `.train()` and `.eval()` method to set the PINA model in train/eval mode. This feature is especially useful for some particular torch modules (Dropout, BatchNorm), see [code](https://pytorch.org/docs/stable/_modules/torch/nn/modules/module.html#Module.train).
=> add train/eval

pina/geometry/cartesian.py, pina/geometry/difference_domain.py, pina/geometry/ellipsoid.py, pina/geometry/union_domain.py, tests/test_cartesian.py, tests/test_ellipsoid.py, tests/test_union.py
Solving bug reported in #117 + fixes to Union class + fix in Difference class + fix in Cartesian class
- `EllipsoidDomain` missed to shift the centers when evaluating if a point is inside, now fixed. Also updating tests.
- `Union` missed to randomly iterate on the geometries when sampling (otherwise for one sample we would sample only from the same first geometry), now fixed.
- `Difference` just minor changes (`is` changed in `==`).
- `CartesianDomain` fix `is_inside` method, so now also `fixed_variables` are checked correctly. Also updating tests.
=> Solving problems related to Geometry 

pina/label_tensor.py, tests/test_label_tensor.py
Updating `LabelTensor` class. Now passing to cuda/cpu and changing dtype is supported in `LabelTensor`. Additionally, we added the possibility to slice the tensor as:
```
labels = ['a', 'b']
data = torch.rand((10, 2))
tensor = LabelTensor(data, labels)
tensor_view = tensor['a']            # same as tensor.extract('a')
```
=> Label Tensor update

pina/__init__.py, pina/callbacks/adaptive_refinment_callbacks.py, pina/callbacks/optimizer_callbacks.py, pina/dataset.py, pina/geometry/simplex.py, pina/label_tensor.py, pina/loss.py, pina/problem/abstract_problem.py, pina/solvers/garom.py, pina/solvers/pinn.py, pina/solvers/solver.py, pina/trainer.py, setup.py, tests/test_callbacks/test_adaptive_refinment_callbacks.py, tests/test_callbacks/test_optimizer_callbacks.py, tests/test_dataset.py, tests/test_label_tensor.py, tests/test_solvers/test_garom.py, tests/test_solvers/test_pinn.py
=> add dataset and dataloader for sample points

pina/plotter.py
Hey guys
As numpy doesn't support GPU yet, I found a way to fix the bug I mentioned in [https://github.com/mathLab/PINA/issues/219](url), using `plt.plot(epochs, loss.cpu(), **kwargs)` instead of `plt.plot(epochs, loss, **kwargs)`
I have tested these changes locally, but I would greatly appreciate it if you could review and provide feedback on the solution I used.
=> fix : gpu loss plotting

pina/plotter.py
Good afternoon,
I found a small bug on the plotter.plot function :
When plotting a function and selecting a single component, like this : 
```python
plotter.plot(pinn,components = 'x1' , fixed_variables = ...)
```
if the variable name is longer than 1 character, an error is thrown because the function expects a list and gets a string, therefore counting the number of characters in it. 
I added a simple check : 
```python
if type(components) is not list:
components = [components]
```
I have tested these changes locally, but I would greatly appreciate it if you could review and provide feedback on the solution I used.
=> fix : check_components_type

docs/source/_rst/_code.rst, docs/source/_rst/models/base_no.rst, docs/source/_rst/models/fourier_kernel.rst, pina/model/__init__.py, pina/model/base_no.py, pina/model/fno.py, tests/test_model/test_base_no.py
* Unifying integral kernel NO architectures with BaseNO (maybe rename better)
* Implement FNO based on BaseNO
=> Unifying integral kernel NO architectures

pina/trainer.py
Fix issue #281: in `pina/trainer.py` add the conversion of device for the unknown parameters in the inverse problem.
=> Fix GPU training in inverse problem

docs/source/_rst/_tutorial.rst, docs/source/_rst/tutorials/tutorial12/tutorial.rst, tutorials/README.md, tutorials/tutorial12/tutorial.ipynb, tutorials/tutorial12/tutorial.py
Equation class tutorial (see #248)
=> Equation Class Tutorial 

pina/solvers/__init__.py, pina/solvers/pinns/competitive_pinn.py, tests/test_solvers/test_competitive_pinn.py
Try to add Competitive PINNs
**TODO**
=> Competitive Pinn Addition

docs/source/_rst/layers/orthogonal.rst, pina/model/layers/orthogonal.py, tests/test_layers/test_orthogonal.py
Add in `model/layers` the `OrthogonalBlock`, performing an orthonormalization on the input matrix in a specified dimension.
It can be useful in model order reduction to make the output columns an orthonormal basis.
=> Add OrthogonalBlock to make input orthonormal

tests/test_operators.py
Solving issue #382.
Tests on actual values and labels for each differential operator are added where missing. All operators are tested both on the whole set of input/output components, and on a representative subset.
=> Additional tests for operators

pina/callbacks/adaptive_refinment_callbacks.py, pina/callbacks/optimizer_callbacks.py, pina/callbacks/processing_callbacks.py, pina/solvers/supervised.py
Update import statements in version 0.2 from 
```python 
from pytorch_lightning
```
to
```python 
from lightning.pytorch
```
in order to avoid error message "Expected a parent" when passing a CallBack in a pina Trainer
=> Update import from lightning.pytorch

pina/model/layers/pod.py, tests/test_layers/test_pod.py
Only replaced the `torch.svd_lowrank` method with `torch.svd`: the reason is that `torch.svd_lowrank` is randomized and may give different results in different runs (as specified in the documentation: [https://pytorch.org/docs/stable/generated/torch.svd_lowrank.html](https://pytorch.org/docs/stable/generated/torch.svd_lowrank.html))
=> Change SVD type in pod.py

pyproject.toml
I realized that `numpy` dependency is not needed, it is already in the requirements of `torch` (https://github.com/pytorch/pytorch/blob/main/pyproject.toml), also I do not think we need `pytorch_lightning` as dependency anymore
=> Modify  pyproject.toml

pina/collector.py, pina/data/data_module.py, pina/data/dataset.py, pina/graph.py, pina/trainer.py, pina/utils.py, tests/test_data/test_datamodule.py
This PR fix some bugs with solvers and Graphs
=> Fix bug in Collector with Graph data

pina/solver/physic_informed_solver/competitive_pinn.py, pina/solver/physic_informed_solver/self_adaptive_pinn.py
Fix #468.
Removed a bug in the `training_step` of `SelfAdaptivePINN`, and removed unneccessary override of `loss_data` in `CompetitivePINN`.
=> Fixing self adaptive pinns 

pina/solver/physic_informed_solver/competitive_pinn.py
* Removing unnecessary training steps
* Fixing for datadriven mode
=> Fixing competitive pinn

pina/callback/__init__.py, pina/callback/linear_weight_update_callback.py, tests/test_callback/test_linear_weight_update_callback.py
Added a callback that allows to linearly adjust the weight of a condition from an initial value to a target value over a specified number of epochs. This only works with `ScalarWeighting` weighting schema.
It would be nice to extend this to allow different updates in addition to the linear one (e.g., exponential or polynomial update).
=> Linear weight update callback

tests/test_solver/test_supervised_solver.py
Add some test for Supervised Solver on Graph based models
=> Add test for supervised solver in graph-based models

pina/callback/adaptive_refinement_callback.py, pina/callback/linear_weight_update_callback.py, pina/callback/optimizer_callback.py, pina/callback/processing_callback.py, pina/trainer.py, tests/test_callback/test_metric_tracker.py, tests/test_callback/test_optimizer_callback.py, tests/test_callback/test_progress_bar.py
In this PR the PINA callbacks and related tests are updated.
The Refinment callback is deprecated, see issue #481
=> Update callbacks and tests

docs/source/_rst/_code.rst, pina/loss/ntk_weighting.py
Due to failing doc workflow in 0.2
https://github.com/mathLab/PINA/actions/runs/13952172103/job/39054273261
=> Doc update NTK

pina/data/data_module.py, pina/data/dataset.py, tests/test_data/test_data_module.py, tests/test_data/test_graph_dataset.py
In this PR, I fix a bug in `get_all_data` function in Dataset. The code for reproducing the issue is the following
```python
input=torch.stack([torch.zeros((1,))+i for i in range(1000)])
target=input
problem = SupervisedProblem(input,target)
datamodule = PinaDataModule(problem,
train_size=0.7,
test_size=0.2,
val_size=0.1,
batch_size=64,
shuffle=False,
repeat=False,
automatic_batching=None,
num_workers=0,
pin_memory=False,)
datamodule.setup('fit')
datamodule.setup('test')
print()
print('Using batch_size 64')
print(f'{(len(datamodule.train_dataset)==700)=}')
print(f'{(len(datamodule.test_dataset)==200)=}')
print(f'{(len(datamodule.val_dataset)==100)=}')
print()
print(f'{(len(datamodule.train_dataset.get_all_data()["data"]["input"])==700)=}')  # <==== False but must be True …
```
=> Bug fix and add additional tests for Dataset and DataModule

pina/operator.py, tests/test_operator.py
=> fix bug in laplace labels

pina/graph.py, tests/test_graph.py
=> Self-loops management in KNNGraph and RadiusGraph

pina/operator.py, tests/test_operator.py
=> Improve differential operators

pina/solver/physics_informed_solver/pinn_interface.py, pina/solver/solver.py
I propose these two changes:
1. Move `add_param_group` of `InverseProblem` parameters from `PINNInterface` to `SingleSolverInterface` since also supervised single solver could in principle solve inverse problems. For multisolver, it is not clear which optimizer needs the parameter to be attached (case specific)
2. `PINNInterface` should inherit from `SupervisedSolverInterface` to avoid code duplication
=> Update PINNInterface Inheritance

pina/label_tensor.py, tests/test_label_tensor/test_label_tensor.py
=> Fix `__getitem__` in LabelTensor

pina/collector.py, pina/condition/condition_interface.py
=> Fix single graph handling

pina/model/block/pod_block.py, tests/test_blocks/test_pod.py
This PR fixes #565 .
This PR adds the singular values as a property in `pina/model/block/pod_block.py`, and the related tests.
=> Add singular values in PODBlock

pina/operator.py, tests/test_operator.py
=> fix advection

pina/problem/abstract_problem.py, tests/test_problem.py
=> fix problem data collection for v0.1

pina/solver/physics_informed_solver/rba_pinn.py, tests/test_solver/test_rba_pinn.py
This PR fixes #588 
In this PR, I have added the support for batching while using `RBAPINN` solver class.
=> Support batching for rbapinns

pina/equation/system_equation.py, tests/test_equations/test_system_equation.py
=> Support built-in Equations in System of Equation

pina/callback/optimizer_callback.py, tests/test_callback/test_optimizer_callback.py
This PR fixes #607 
Issue summary, for reference: While `solver.optimizer` was successfully updated, `trainer.strategy.optimizers` was not. As a result, PyTorch Lightning continued using the original optimizer during training, effectively ignoring the switch.
=> Fix switch_optimizer callback

pina/solver/physics_informed_solver/self_adaptive_pinn.py, tests/test_solver/test_self_adaptive_pinn.py
=> Add batching support for self-adaptive pinns

docs/source/_rst/_code.rst, docs/source/_rst/model/block/pirate_network_block.rst, docs/source/_rst/model/pirate_network.rst, pina/model/__init__.py, pina/model/block/__init__.py, pina/model/block/pirate_network_block.py, pina/model/pirate_network.py, tests/test_blocks/test_pirate_network_block.py, tests/test_model/test_pirate_network.py
=> Add pirate network

pina/model/block/pod_block.py, tests/test_block/test_pod.py
=> Fix basis device transfer in PODBlock

pina/equation/equation_factory.py
PR #645 introduces several codacy warnings with code R0903. This PR disable those warning since the code correctly implements the equations.
=> Disable `R0903` warning in `equation_factory.py`
