- examples/problems/stokes.py
- examples/run_stokes.py
- pina/condition.py
- pina/label_tensor.py
- pina/model/feed_forward.py
- pina/pinn.py
- pina/plotter.py
- pina/span.py
- add possibility to deal with vector output
- add Stokes example
> Vectorial output

- pina/model/network.py
> docstring correction

- pina/model/deeponet.py
- tests/test_deeponet.py
> Remove parameter inner_size from DeepONet constructor

- pina/pinn.py
- pina/utils.py
- Simplified `merge_tensors`
- Code cleanup
> Minor cleanup

- pina/span.py
> Select variables to be used as labels in `_Nd_sampler` 

- pina/utils.py
- tests/test_utils.py
Fixing the bug I introduced in #45 (missing import statement).
> Add missing impor statements and test on `merge_tensors`

- pina/span.py
- pina/utils.py
- tests/test_pinn.py
Implemented latin hypercube sampling. Solving #41. For the implementation I followed the `scipy` [code](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.qmc.LatinHypercube.html). With this pull request we also remove the dependency of PINA from `scipy`. Tests added as well.
> solving latin hypercube sampling

- pina/pinn.py
- pina/span.py
- tests/test_pinn.py
With this pull request we fix #54 , and other bugs associated with `pinn.sample`.
> solving span bugs

- tutorials/README.md
Fix #60 . For now the link is working for tutorial 2 and 3. As soon as the docs page is updated (roughly once per month) also tutorial 1 will appear.
> README.md for tutorials

- docs/source/_rst/tutorial1/tutorial.rst
- docs/source/_rst/tutorial3/tutorial.rst
- tutorials/tutorial3/tutorial.ipynb
- tutorials/tutorial3/tutorial.py
Fix equation in tutorial 3 + minor changes in rst file for tutorial 1
> Tutorial3 fix

- examples/run_poisson_deeponet.py
- pina/model/deeponet.py
- pina/model/feed_forward.py
- pina/utils.py
- tests/test_deeponet.py
In this PR I'm introducing the model which I developed based on @ndem0's idea to generalize DeepONet (https://doi.org/10.1038/s42256-021-00302-5). 
Instead of brunch and trunk we consider a variable number of internal networks, and we enable additional flexibility on aggregation and reduction.
> Generic DeepONet

- examples/run_stokes.py
> update pinn loss histroy attribute to history_loss

- docs/source/_rst/abstractproblem.rst
- docs/source/_rst/code.rst
- docs/source/_rst/multifeedforward.rst
- docs/source/_rst/parametricproblem.rst
- docs/source/_rst/spatialproblem.rst
- docs/source/_rst/timedepproblem.rst
- pina/model/multi_feed_forward.py
- pina/problem/abstract_problem.py
- pina/problem/parametric_problem.py
- pina/problem/spatial_problem.py
- pina/problem/timedep_problem.py
Add documentation for `model/multi_feed_forward.py`, `problem/abstract_problem.py`, `problem/spatial_problem.py`, `problem/timedep_problem.py`, `problem/parametric_problem.py`.
Partially solving #78.
> Partially fix documentation

- docs/source/_rst/code.rst
- docs/source/_rst/network.rst
- pina/problem/parametric_problem.py
Fix typo in documentation for `problem/parametric_problem.py` and `model/network.py` in `_rst` folder.
> Minor fix to documentation

- pina/pinn.py
- setup.py
- tests/test_pinn.py
PINA tests with cpu for PINN.
Currently we are checking training using default accelerator. We make tests only for CPU to make it more robust, and be sure that the behaviour for CPU is corrected
> check train test

- pina/problem/abstract_problem.py
- tests/test_solvers/test_pinn.py
Fixing the bug introduced in commit b3f7b16f50cd7820b7935a4947adfe072429f11f and highlighted in https://github.com/mathLab/PINA/issues/138#issuecomment-1612478049
> Fix Bug variables sampling

- pina/equation/__init__.py
- pina/equation/equation.py
- pina/equation/equation_factory.py
- pina/equation/system_equation.py
- tests/test_equations/test_equation.py
- tests/test_equations/test_systemequation.py
- add init file
- add docs
- fixing bug System of equation, replace torch.stack with torch.hstack
- add tests
> Enhancing Equations

- pina/geometry/difference_domain.py
- pina/geometry/exclusion_domain.py
- pina/geometry/intersection_domain.py
- pina/geometry/operation_interface.py
- pina/geometry/union_domain.py
- added set notation to all the geometry operations
- added a warning to say sample_surface=True doesn't work
> Operation documentation enhancement 

- pina/solvers/pinn.py
Temporary fix for a simple logger
> Simple Logger for PINN

- pina/geometry/__init__.py
- pina/geometry/simplex.py
- tests/test_geometry/test_simplex.py
* Simplex Domain
* Tests
* Init
> Simplex Domain

- examples/problems/parametric_elliptic_optimal_control_alpha_variable.py
- examples/problems/parametric_poisson.py
- examples/problems/poisson.py
- examples/problems/stokes.py
- pina/equation/equation_factory.py
- pina/operators.py
- pina/problem/timedep_problem.py
- tests/test_condition.py
- tests/test_equations/test_equation.py
- tests/test_equations/test_systemequation.py
- tests/test_geometry/test_cartesian.py
- tests/test_operators.py
- tests/test_problem.py
- tests/test_solvers/test_pinn.py
- tutorials/tutorial2/tutorial.py
- tutorials/tutorial3/tutorial.py
Solves #160.
It also includes a minor documentation fix in the `advection()` operator.
> Rename nabla -> laplacian

- .github/workflows/testing_pr.yml
- pina/label_tensor.py
- tests/test_label_tensor.py
> fix slicing for LabelTensor

- pina/trainer.py
- tests/test_solvers/test_garom.py
- tests/test_solvers/test_pinn.py
* the arguments of `Trainer.train` now are passed to the fit 
* unittest for load/restoring from checkpoint
> Trainer `train` simplified, tests for load 

- pina/callbacks.py
- pina/callbacks/__init__.py
- pina/callbacks/adaptive_refinment_callbacks.py
- pina/callbacks/optimizer_callbacks.py
- pina/problem/abstract_problem.py
- pina/trainer.py
- tests/test_callbacks/test_adaptive_refinment_callbacks.py
- tests/test_callbacks/test_optimizer_callbacks.py
* Implementing a callback to switch between optimizers during training
* Implementing the R3Refinment for collocation points
* Modify trainer -> dataloader is created or updated by calling `_create_or_update_loader`
* Adding `add_points` routine to AbstractProblem so that new points can be added without resampling from scratch
> Multiple callbacks impelementation

- pina/geometry/simplex.py
- tests/test_geometry/test_simplex.py
We solved #179 in this pull request.
* Solving the issue
* Adding the `sample()` test
> Solving #179 Simplex Domain Bug

- pina/solvers/garom.py
Adding the possibility to log mean loss/ generator loss/ discriminator loss/ stability metric.
> GAROM loggers

- pina/geometry/cartesian.py
> Added 'sample_surface' parameter to CartesianDomain

- pina/geometry/cartesian.py
This reverts commit a2ea9ff5ec564b54bc73b5200712661c2e5dcbf6.
> Revert "Added 'sample_surface' parameter to CartesianDomain (#190)"

- pina/geometry/simplex.py
- tests/test_geometry/test_simplex.py
> Solving SimplexDomain error when n_vertices > 3

- pina/plotter.py
Commented a line responsible for bugs. No labels attribute in torch.Tensor object
> Plotter v0.1 update

- pina/solvers/garom.py
* Removing `retain_graph` in backward for discriminator
* Fixing issues with different precision training for Lightining
> minor updates in garom.py

- pina/condition.py
* minor update in the ValueError message
> Update condition.py error message

- pina/plotter.py
- tests/test_plotter.py
Solving problems in 1d and 2d plots
> Update plotter class

- docs/source/_rst/tutorials/tutorial6/tutorial.rst
- tutorials/tutorial6/tutorial.ipynb
- tutorials/tutorial6/tutorial.py
> Fix typo tutorial geometry

- pina/solvers/__init__.py
- pina/solvers/pinns/causalpinn.py
- tests/test_solvers/test_causalpinn.py
* Adding the `CausalPINN` class
* Adding tests for `CausalPINN` class
> Causal PINN

- pina/solvers/__init__.py
- pina/solvers/rom.py
- pina/solvers/supervised.py
- tests/test_solvers/test_rom_solver.py
* Adding rom solver with end to end training
* Adding test
* restructure init file solvers
> Adding ReducedOrderModelSolver

- pina/benchmarks/problems/__init__.py
- pina/benchmarks/problems/poisson.py
> Poissson->Poisson

- setup.py
> Update setup.py for python versions

- docs/source/_rst/_code.rst
- docs/source/_rst/solvers/rba_pinn.rst
- pina/solvers/__init__.py
- pina/solvers/pinns/__init__.py
- pina/solvers/pinns/rbapinn.py
- setup.py
- tests/test_solvers/test_rba_pinn.py
Residual-based attention pinn solver. Solving #304 . Paper:  https://arxiv.org/abs/2307.00379
> added rba-pinn

- pina/problem/abstract_problem.py
- tests/test_problem.py
Solving issue #309 with `add_points`.
> Solving issue #309

- pina/model/layers/embedding.py
Adding gpu to fourier embedding
> gpu fourierembedding

- pina/model/layers/__init__.py
- pina/model/layers/orthogonal.py
- tests/test_layers/test_orthogonal.py
Fixing #328 and adding compatibility for backpropagation in `OrthogonalBlock`
> Backpropagation for OrthogonalBlock

- docs/source/_rst/_installation.rst
- docs/source/conf.py
- docs/source/index.rst
- setup.py
* Fix typos and mail link in the documentation
* Adding `sphinx_design` in the `setup.py` file
> Fixing documentation

- docs/source/_team.rst
> Fix typo in documentation

- pina/model/deeponet.py
- tests/test_model/test_deeponet.py
Just modifying `pina/model/deeponet.py` such that it can have more than one output. This resolves #326
> Add multiple outputs possibility in DeepONet

- pina/label_tensor.py
- pina/solvers/__init__.py
- pina/solvers/pinns/basepinn.py
- pina/solvers/pinns/pinn.py
- pina/solvers/solver.py
- pina/solvers/supervised.py
- pina/trainer.py
> Revert "Fix bugs"

- pina/geometry/cartesian.py
- pina/geometry/ellipsoid.py
- pina/geometry/simplex.py
> Sorting Variables for Geometries

- pina/domain/cartesian.py
- pina/domain/ellipsoid.py
- pina/domain/operation_interface.py
- pina/domain/simplex.py
- pina/domain/union_domain.py
Fix #391.
Most changes are similar to issue #377, successfully closed.
> Sorting the labels of variables in domain operations

- pina/operators.py
- tests/test_operators.py
> Fix laplacian

- pina/label_tensor.py
- tests/test_label_tensor/test_label_tensor.py
This PR simplifies and add doctoring to the LabelTensor class, fix issue #395  and resolves a compatibility issue in tests
> Simplify LabelTensor class

- pina/data/data_module.py
Reverts mathLab/PINA#425, more updates needed.
> Revert "Bug fix PR #423"

- tutorials/tutorial12/tutorial.ipynb
Updated tutorial12 to make it work with the domain folder:
- Deleted unused imports
- Imported CartesianDomain from pina.domain (used to be pina.geometry)
- Changed key inputs of Condition
- Minor text changes
> Update tutorial12 to work with domain folder (#421)

- pina/problem/zoo/__init__.py
- pina/problem/zoo/supervised_problem.py
- tests/test_problem_zoo/test_supervised_problem.py
In this PR I added the Supervied Problem class into problem zoo. This class allows a simpler definition of a problem with a single conditon of type InputOutputPointsCondition
> Supervised Problem

- .github/workflows/tutorial_exporter.yml
- pyproject.toml
> tutorial exporter update

- .github/workflows/monthly-tagger.yml
- .github/workflows/tester.yml
- .github/workflows/tutorial_exporter.yml
- pyproject.toml
> rm py3.8, add 3.13

- tutorials/tutorial21/tutorial.ipynb
- tutorials/tutorial8/tutorial.ipynb
> fix link tutorials

- README.md
> Fix ReadMe examples

- pina/equation/equation.py
- pina/solver/physics_informed_solver/pinn_interface.py
> simplify kwargs logic for equations

- pina/operator.py
- tests/test_operator.py
> Pass `method` argument to `fast_laplacian`
